### ISSUE TITLE
Error when 'error' returned by the API

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/TrasportAPI-HASS#1]
An invalid requested to the API will return something like `{'error': "station code 'MAL235' assumed to be a CRS code, but is not exactly 3 chars"}`. This resulted in the error `ValueError: min() arg is an empty sequence` and the sensor not being updated. This is fixed (trains only) in e2c97a8cad781b59ecdad800dbd5f7070a9b484f by the addition in update() of:
```
        if 'error' in self._data:          # if query returns an error
                self._state = 'Error in query' 
```

And the frontend will show:

![image](https://user-images.githubusercontent.com/11855322/27118449-31550eea-50d3-11e7-8eac-9e2ec3cf61ee.png)

To do: add logging

**Comment by robmarkcole** [comment]
@michaelmcarthur is this fixed for you now?

**Comment by michaelmcarthur** [comment]
Tested a non CRS code and I got `Error in Query` in the front end. This is great for debugging.
