### ISSUE TITLE
Station Error

### ISSUE THREAD

**Issue by michaelmcarthur** [robmarkcole/TrasportAPI-HASS#2]
If I put in a destination station that is not a the end of the route the senor fails. I found a way found this. If line 220 is changed in uk_transport.py is changed from:

`        params = {'darwin': 'false', 'destination': self._destination_name, 'train_status': 'passenger'}`

to

`        params = {'darwin': 'false', 'calling_at': self._destination_name, 'train_status': 'passenger'}`

This gives flexibility into using any stop on the line. What do you think @robmarkcole ?

**Comment by robmarkcole** [comment]
Agreed, sounds better approach. Can you submit a pull request so I can see all changes you are making?

**Comment by michaelmcarthur** [comment]
Pull request completed

**Comment by robmarkcole** [comment]
Made a comment on it. Technically the request is completed when merged I suppose.
Cheers
