### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/TrasportAPI-HASS#8]
Limited to 1000 requests per day on free transportAPI plan. 

Proposed solution is to add to config time windows when:

1. the sensor should refresh at the max rate - every minute, e.g. 1 hour around commute times
2. The sensor should not refresh at all - e.g. midnight to 5 am

Add method to calculate the refresh rate for all other times such that the total daily limit is not exceeded.

**Comment by michaelmcarthur** [comment]
I have been trying to get this to work for the last hour. I'm really struggling to find a way to do this. I will be  interested in how this is achieved.

**Comment by robmarkcole** [comment]
`SCAN_INTERVAL = timedelta(minutes=1)` is a per platform parameter so need to make use of:
`from homeassistant.util import Throttle`

To do: study https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/darksky.py 

And: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/dht.py

Forum advice from @trisk

> if you can have a single data object with the "real" update implementation (e.g. instantiated in your setup_platform and passed to each sensor entity created) homeassistant.util.Throttle can be used on the real update method as a decorator, which effectively creates a single TTL
(and you can specify any timedelta for that)
(and your sensor object's update methods call yourdataobject.update() which becomes a no-op when throttled)
this appears to be actually what darksky does
sensor.dht looks like a more concise example

**Comment by robmarkcole** [comment]
![image](https://user-images.githubusercontent.com/11855322/27166567-a13ced98-5193-11e7-8ec6-f04e811a0c70.png)
![image](https://user-images.githubusercontent.com/11855322/27166570-a520f710-5193-11e7-89ca-fb80f382ea9f.png)
![image](https://user-images.githubusercontent.com/11855322/27166573-a932f40c-5193-11e7-9d0c-9037e3008ca5.png)

**Comment by michaelmcarthur** [comment]
I think the throttle method shound the right way to go. In the [verisure](https://github.com/home-assistant/home-assistant/blob/3ee4d1060fdbe067c19f7d4ce4777a7eb9dbb412/homeassistant/components/verisure.py) sensor it has multiple throttles for different attributes. I thought that using if statements it could throttle depending on time set by user. Or how about the sensor updates its frequency if it is being viewed on the front end. I believe the camera component does this.

**Comment by robmarkcole** [comment]
Thanks for the info, will check it out 👍

**Comment by robmarkcole** [comment]
Ok I think this should be pretty straightforward. The main decision is how much control to give the user to set the refresh rate. I think for each sensor, optional config entries for: 

* A peak time window: update every minute by default
* an off time window: by default midnight- 5am

If a user doesn't  set any time windows and only has 1 sensor this will happily update at peak rate all day.

setup() determines the off-peak refresh rate.

Thoughts?

**Comment by michaelmcarthur** [comment]
Sounds good. I think it's right not to give too much control. In my opinion an optional peak and offpeak is the right level of update and control. 

If a user does not select any time windows. They will still run into usage limits. By default the sensor would update 1140 times (19 hours on, 5 hours off). Change the default update to 90 seconds the sensor would update 760 times.

**Comment by robmarkcole** [comment]
Posted query about handling user entry of time windows on https://community.home-assistant.io/t/time-window-entry-in-config/19897

Proposed entry:

```
On peak
  - 07:00 
  - 09:00
Off peak
  - 19:00
  - 23:00
```

On and Off peak could be confused for train conditions, better names could be:
1. Priority refresh window
2. No updates window

**Comment by robmarkcole** [comment]
Will need to create services which: 
* Allow the user to disable updates
* Set the throttle rate on a per sensor basis

**Comment by Pow377** [comment]
I think a day and timeframe setting would be good per query.

There are still some challenges (would need multiple queries if needing to set up multiple time frames or a workaround for it)

Potential to hit rate limit so a default would need to be in place

Weekdays:
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
Starting: '07:00:00'
Ending:   '09:00:00'

Limiting to no updates between midnight and 5am potentially kills chance of usage by night shift workers who may use night buses etc.

**Comment by robmarkcole** [comment]
To do: add service to allow updating the `interval` from an automation. The user will be responsible for managing their API allowance

**Comment by robmarkcole** [comment]
This can be handled by HA using `homeassistant.update_entity`
