### ISSUE TITLE
Error if no departures

### ISSUE THREAD

**Issue by michaelmcarthur** [robmarkcole/TrasportAPI-HASS#9]
If there is no departures eg at night when the trains are not running. This error occurs.

```
  File "/home/pi/.homeassistant/custom_components/sensor/uk_transport.py", line 241, in update
    _delta_mins, [train['scheduled'] for train in self._next_trains]
ValueError: min() arg is an empty sequence
```

This is the json for the request.

`{"date":"2017-06-14","time_of_day":"23:54","request_time":"2017-06-14T23:54:31+01:00","station_name":"REDACTED","station_code":"REDACTED","departures":{"all":[]}}`

Looks like it needs and else argument if departures are zero.

**Comment by robmarkcole** [comment]
Should be fixed in fa58249272c8c0d17e148544f256b7f4b5718285

**Comment by michaelmcarthur** [comment]
Thank you for fixing so quickly. The code looks good. I'll test it tonight once the trains on my route have finished.

**Comment by michaelmcarthur** [comment]
I have tested this same issue tonight. The template sensor updated with the last value then never updated to no data. E.g. The last train was at 2315. Then by 2330 it was still displaying 2315.  The uk_transport sensor shows that there is no more trains but the template does not update.

Same issue as last night. When there is no trains and I restart the uk_transport sensor fails. Error log shows the same  information as the first comment.

**Comment by robmarkcole** [comment]
I see what was wrong, I think.. Can you try bee67bd099a1746cf28ba9c783934ca38de55423 ?

**Comment by michaelmcarthur** [comment]
Will do. I will give an update once the last train has run tonight.

**Comment by robmarkcole** [comment]
Requesting data for a time window when there are no trains scheduled should be equivalent

**Comment by michaelmcarthur** [comment]
This update has solved the issue. It now displays "No Departures" as its state. On a restart the sensor starts as expected. I'll check in the morning if the sensor starts updating once the trains have started again.

**Comment by michaelmcarthur** [comment]
Everything is working this morning. I would merge these changes to the main branch. Good work.

**Comment by robmarkcole** [comment]
Done. Will keep development to the Dev branch going forward
